# Generated by Django 5.2.12 on 2026-03-05 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0002_initial"),
        ("laboratory", "0001_initial"),
        ("organization", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_orders",
                to="encounters.encounter",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="ordered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_orders",
                to="users.practitionerprofile",
            ),
        ),
        migrations.AddField(
            model_name="laborderitem",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="organization.clinic",
            ),
        ),
        migrations.AddField(
            model_name="laborderitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laborderitem",
            name="lab_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="laboratory.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="organization.clinic",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="lab_order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="laboratory.laborderitem",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_lab_results",
                to="users.practitionerprofile",
            ),
        ),
        migrations.AddField(
            model_name="labtestcatalogue",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="organization.clinic",
            ),
        ),
        migrations.AddField(
            model_name="labtestcatalogue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laborderitem",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="laboratory.labtestcatalogue",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborderitem",
            constraint=models.UniqueConstraint(
                fields=("clinic", "lab_order", "lab_test"),
                name="uniq_lab_test_per_order_per_clinic",
            ),
        ),
    ]
