# Generated by Django 5.2.12 on 2026-04-25 12:22

import organization.models
from django.db import migrations, models
from django.utils.crypto import get_random_string

def gen_unique_code(apps, schema_editor):
    Clinic = apps.get_model("organization", "Clinic")
    for clinic in Clinic.objects.all():
        clinic.code = get_random_string(length=6, allowed_chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        while Clinic.objects.filter(code=clinic.code).exists():
            clinic.code = get_random_string(length=6, allowed_chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        clinic.save(update_fields=["code"])

class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="code",
            field=models.CharField(
                default=organization.models.generate_clinic_code,
                max_length=6,
                null=True,
            ),
        ),
        migrations.RunPython(gen_unique_code, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clinic",
            name="code",
            field=models.CharField(
                default=organization.models.generate_clinic_code,
                max_length=6,
                unique=True,
            ),
        ),
    ]
