apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avocent.fullname" . }}-backend
  labels:
    {{- include "avocent.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "django.secretKey is required" .Values.django.secretKey | quote }}
  DB_PASSWORD: {{ required "postgres.password is required" .Values.postgres.password | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
  FIELD_ENCRYPTION_KEY: {{ required "django.fieldEncryptionKey is required" .Values.django.fieldEncryptionKey | quote }}
  API_ENCRYPTION_KEY: {{ .Values.django.apiEncryption.key | quote }}
