{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "avocent.fullname" . }}
  labels:
    {{- include "avocent.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.apiHost }}
    - host: {{ .Values.ingress.apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "avocent.webService" . }}
                port:
                  name: http
    {{- end }}
    {{- if .Values.ingress.appHost }}
    - host: {{ .Values.ingress.appHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "avocent.fullname" . }}-frontend
                port:
                  name: http
    {{- end }}
{{- end }}
