# Generated by Django 5.2.12 on 2026-06-30 21:24

from django.db import migrations


def add_accountant_role(apps, schema_editor):
    Clinic = apps.get_model("organization", "Clinic")
    Role = apps.get_model("users", "Role")
    for clinic in Clinic.objects.all():
        Role.objects.get_or_create(
            clinic=clinic,
            name="Accountant",
            defaults={"description": "Full billing, payments, and financial reporting access."},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_accountant_role, migrations.RunPython.noop),
    ]
