# Generated by Django 5.2.12 on 2026-09-02 04:21

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_practitionerprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=core.fields.EncryptedTextField(blank=True, default=""),
        ),
    ]
