"""
Django settings for avocent_backend project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""

import os

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent


def _get_env(name: str, default: str | None = None, required: bool = False) -> str | None:
    value = os.environ.get(name, default)
    if required and value is None:
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return value


def _get_bool_env(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def _get_list_env(name: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(name)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


REDIS_URL = _get_env("REDIS_URL")


def get_databases() -> dict:
    """Build DATABASES based on environment variables.

    The backend uses PostgreSQL for all environments.
    """

    engine = _get_env("DB_ENGINE", "django.db.backends.postgresql")

    if engine in ("django.db.backends.postgresql", "django.db.backends.postgresql_psycopg2"):
        # Unset by default: psycopg3's own default (sslmode=prefer) is left alone for local
        # dev. Managed Postgres (e.g. Azure Database for PostgreSQL) requires TLS, so
        # staging/prod set this to "require" rather than relying on opportunistic negotiation.
        sslmode = _get_env("DB_SSLMODE", "")
        options = {"sslmode": sslmode} if sslmode else {}
        return {
            "default": {
                "ENGINE": engine,
                "NAME": _get_env("DB_NAME", "avocent_healthcare"),
                "USER": _get_env("DB_USER", "brianmunene"),
                "PASSWORD": _get_env("DB_PASSWORD", ""),
                "HOST": _get_env("DB_HOST", "localhost"),
                "PORT": _get_env("DB_PORT", "5432"),
                "OPTIONS": options,
            }
        }

    raise ImproperlyConfigured(
        f"Unsupported DB_ENGINE '{engine}'. Supported engine is postgresql."
    )

SECRET_KEY = _get_env(
    "SECRET_KEY",
    "django-insecure-@5y6+tg=vi)cd!3d+6q%ssq7beykd2%fk5dg(q21i6na!&w3bp",
)
DEBUG = _get_bool_env("DEBUG", default=True)
ALLOWED_HOSTS = _get_list_env("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# TLS / security hardening — off by default so local dev (no reverse proxy in front) is
# unaffected; staging/prod turn these on since Caddy terminates TLS in front of `web`.
SECURE_SSL_REDIRECT = _get_bool_env("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = _get_bool_env("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = _get_bool_env("CSRF_COOKIE_SECURE", default=False)
SECURE_HSTS_SECONDS = int(_get_env("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = _get_list_env("CSRF_TRUSTED_ORIGINS", default=[])

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework.authtoken",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "core",
    "organization",
    "users",
    "patients",
    "booking",
    "encounters",
    "clinical",
    "billing",
    "payments",
    "pharmacy",
    "laboratory",
    "telemedicine",
    "audit",
    "notifications",
    "compliance",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "core.middleware.APIEncryptionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "audit.middleware.AuditActorMiddleware",
    "users.middleware.RBACMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "avocent_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "avocent_backend.wsgi.application"

DATABASES = get_databases()

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "avocent-backend-local-cache",
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

APPEND_SLASH = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Avocent Backend API",
    "DESCRIPTION": "Clinic-first HIMS and telemedicine API for Avocent Health Centre.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "TAGS": [
        {"name": "Authentication", "description": "Login, logout, token issuance, and current-user endpoints."},
        {"name": "User Administration", "description": "Users, roles, practitioner profiles, and role assignments."},
        {"name": "Patient Records", "description": "Patient demographics, identifiers, allergies, and chronic conditions."},
        {"name": "Bookings & Flow", "description": "Operational patient journey from arrival and triage through billing and checkout."},
        {"name": "Appointments & Encounters", "description": "Scheduling, visits, and encounter-centered nested workflows."},
        {"name": "Clinical Documentation", "description": "Clinical notes, diagnoses, and observations."},
        {"name": "Billing & Payments", "description": "Services, invoices, invoice lines, and payment collection."},
        {"name": "Pharmacy", "description": "Medications, stock, and prescription workflows."},
        {"name": "Laboratory", "description": "Lab catalogues, orders, items, and results."},
        {"name": "Telemedicine", "description": "Remote sessions and chat session state."},
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
}

API_ENCRYPTION_ENABLED = _get_bool_env("API_ENCRYPTION_ENABLED", default=False)
API_ENCRYPTION_ENFORCE = _get_bool_env("API_ENCRYPTION_ENFORCE", default=False)

CELERY_BROKER_URL = _get_env("CELERY_BROKER_URL", REDIS_URL or "memory://")
CELERY_RESULT_BACKEND = _get_env("CELERY_RESULT_BACKEND", REDIS_URL or "cache+memory://")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = _get_bool_env("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = _get_bool_env("CELERY_TASK_EAGER_PROPAGATES", default=True)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# `celery`/`redis` being importable (core.tasking.CELERY_AVAILABLE) doesn't mean a real broker is
# reachable: without REDIS_URL, CELERY_BROKER_URL falls back to the in-process "memory://" transport,
# which silently drops anything scheduled with an `eta` since nothing else can consume from it. Code
# that needs to know whether delayed/scheduled tasks will actually be delivered should check this flag.
CELERY_BROKER_CONFIGURED = bool(REDIS_URL)

EMAIL_BACKEND = _get_env("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = _get_env("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(_get_env("EMAIL_PORT", "587"))
EMAIL_USE_TLS = _get_bool_env("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = _get_env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = _get_env("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = _get_env("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@avocent.health")
# Auth-less SMTP servers (e.g. a local Mailpit) need the explicit override,
# since the credential-based default would read as "not configured".
EMAIL_CONFIGURED = _get_bool_env(
    "EMAIL_CONFIGURED", default=bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
)

# Base URL of the frontend app, used to build links embedded in outgoing emails
# (e.g. the password reset link).
FRONTEND_URL = _get_env("FRONTEND_URL", "http://localhost:3000")
PASSWORD_RESET_TIMEOUT = int(_get_env("PASSWORD_RESET_TIMEOUT", str(60 * 60 * 24)))

TELEMEDICINE_CHAT_STATE_CACHE_TIMEOUT = int(
    _get_env("TELEMEDICINE_CHAT_STATE_CACHE_TIMEOUT", "43200")
)
APPOINTMENT_REMINDER_LEAD_MINUTES = int(
    _get_env("APPOINTMENT_REMINDER_LEAD_MINUTES", "1440")
)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": [],
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "logs/app.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "patients": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "clinical": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "encounters": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "billing": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pharmacy": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "laboratory": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "telemedicine": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
