# Generated by Django 5.2.12 on 2026-05-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="booking.booking",
            ),
        ),
    ]
