# Generated by Django 5.2.12 on 2026-06-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_medication_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="generic_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medication",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="is_controlled",
            field=models.BooleanField(default=False),
        ),
    ]
