# Generated by Django 5.2.12 on 2026-05-03 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0002_initial"),
        ("organization", "0002_clinic_code"),
        ("patients", "0003_alter_patient_phi_fields"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("booking_number", models.CharField(max_length=20)),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk In"),
                            ("scheduled", "Scheduled"),
                            ("telemedicine", "Telemedicine"),
                        ],
                        default="walk_in",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reception", "Reception"),
                            ("public_portal", "Public Portal"),
                            ("call_center", "Call Center"),
                            ("internal_referral", "Internal Referral"),
                        ],
                        default="reception",
                        max_length=30,
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In Person"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("arrived", "Arrived"),
                            ("waiting_triage", "Waiting Triage"),
                            ("in_triage", "In Triage"),
                            ("waiting_consultation", "Waiting Consultation"),
                            ("in_consultation", "In Consultation"),
                            ("awaiting_disposition", "Awaiting Disposition"),
                            ("waiting_lab", "Waiting Lab"),
                            ("in_lab", "In Lab"),
                            ("waiting_pharmacy", "Waiting Pharmacy"),
                            ("in_pharmacy", "In Pharmacy"),
                            ("waiting_billing", "Waiting Billing"),
                            ("not_paid", "Not Paid"),
                            ("ready_for_checkout", "Ready For Checkout"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_paid", "Not Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                        ],
                        default="not_paid",
                        max_length=20,
                    ),
                ),
                ("triage_required", models.BooleanField(default=True)),
                ("reason_for_visit", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("triage_start_time", models.DateTimeField(blank=True, null=True)),
                ("triage_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_end_time", models.DateTimeField(blank=True, null=True)),
                ("checkout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="encounters.appointment",
                    ),
                ),
                (
                    "assigned_practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="users.practitionerprofile",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organization.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("event_type", models.CharField(max_length=80)),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(blank=True, max_length=30)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="booking.booking",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organization.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_events_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="BookingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("reception", "Reception"),
                            ("triage", "Triage"),
                            ("consultation", "Consultation"),
                            ("laboratory", "Laboratory"),
                            ("pharmacy", "Pharmacy"),
                            ("billing", "Billing"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("entered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_queues",
                        to="users.practitionerprofile",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_booking_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="booking.booking",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organization.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("entered_at", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("clinic", "booking_number"),
                name="uniq_booking_number_per_clinic",
            ),
        ),
    ]
