# Generated by Django 5.2.12 on 2026-03-05 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("organization", "0001_initial"),
        ("patients", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="practitioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="users.practitionerprofile",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encounters",
                to="encounters.appointment",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="organization.clinic",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="practitioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encounters",
                to="users.practitionerprofile",
            ),
        ),
    ]
